# Generated by Django 5.1 on 2024-08-12 16:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='attachments/')),
            ],
        ),
        migrations.CreateModel(
            name='InBox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(choices=[('yandex', 'Yandex'), ('gmail', 'Gmail'), ('mail', 'Mail.ru')], max_length=10)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('subject', models.CharField(max_length=255)),
                ('sent_date', models.DateTimeField()),
                ('received_date', models.DateTimeField(blank=True, null=True)),
                ('body', models.TextField()),
                ('attachments', models.ManyToManyField(blank=True, to='app.attachment')),
                ('inbox', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='app.inbox')),
            ],
        ),
    ]
